### ISSUE TITLE
LifeGameWeb.wasm not found

### ISSUE THREAD

**Issue by aaronjedwards** [kateinoigakukun/life-game-with-swiftwasm#5]
Hey there! I was looking to get this example up and running and I have had a couple of issues.

The first one I was able to resolve, but thought I would point it out if others are having the same issue:
```
ERROR in Entry module not found: Error: Can't resolve '/Users/aaronjedwards/Downloads/life-game-with-swiftwasm-master/static' in '/Users/aaronjedwards/Downloads/life-game-with-swiftwasm-master'
```
The `HtmlWebpackPlugin` was only pointing to the root of the directory where the HTML template was stored instead of the template file itself so I changed the plugin instance in `webpack.config.js` to:

```js
...
new HtmlWebpackPlugin({
      template: staticPath + "/index.html",
 }),
...
```

And that fixed my first issue!

But even though everything builds properly now, I am getting a 404 in browser when looking for `LifeGameWeb.wasm`, as if its not actually output from the build process.

Is there a build step missing in your instructions or something that I am not understanding? Any help is appreciated!

**Comment by aaronjedwards** [comment]
So I was able to properly get the `LifeGameWeb.wasm` file compiled and properly built (turns out my version of swift didnt match the version in `.swiftversion`), but now I am experiencing a different issue:

`LinkError: WebAssembly.instantiate(): Import #5 module="javascript_kit" function="swjs_instanceof" error: function import requires a callable`

Let it be know that I _am_ using the latest development snapshot of swift wasm (wasm-5.3-SNAPSHOT-2020-08-20-a). I tried to build using the version specified in the projects `.swiftversion` (wasm-DEVELOPMENT-SNAPSHOT-2020-04-27-a) but got an error when trying to install it with swiftenv (`tar: Error opening archive: Unrecognized archive format`).

**Comment by MaxDesiatov** [comment]
I guess the reason for the issues you're seeing is that the JavaScriptKit version specified in `Package.swift` does not match the JavaScriptKit runtime version pulled by `npm install`. I think that using [`carton`](https://carton.dev) instead of `npm` and webpack.js is much simpler, and `carton` also warns about the runtime version mismatch. I hope #6 is merged eventually, and the state of the code should work as it is in that PR. Otherwise, please let me know, I'll update the PR as needed.
